apiVersion: integration/v1
kind: Step
name: azure-network-step-load-balancer-delete
version: 1
summary: Delete load balancer

description: |

build:
  apiVersion: build/v1
  kind: Docker

publish:
  repository: relaysh/azure-network-step-load-balancer-delete
