apiVersion: integration/v1
kind: Step
name: azure-network-step-load-balancer-delete
version: 1
summary: Delete load balancer

description: |

build:
  apiVersion: build/v1
  kind: Docker

publish:
  repository: relaysh/azure-network-step-load-balancer-delete

schemas:
  spec:
    source: file
    file: spec.schema.json

examples:
- summary: Delete Azure load balancer
  content:
    apiVersion: v1
    kind: Step
    name: delete-load-balancers
    image: relaysh/azure-network-step-load-balancer-delete
    spec:
      azure:
        connection: !Connection { type: azure, name: my-azure-account }
      waitForDeletion: true
      resourceIDs:
      - !Parameter resourceID