apiVersion: container/v1
kind: StepContainer
inherit: ../hack/defs/azure-python
title: List Azure Load Balancers by SubscriptionId
description: >
  This task describes the Azure Load Balancers in a given Subscription.
