apiVersion: integration/v1
kind: Step
name: azure-network-step-load-balancer-list
version: 1
summary: List load balancer

description: |

build:
  apiVersion: build/v1
  kind: Docker

publish:
  repository: relaysh/azure-network-step-load-balancer-list

schemas:
  spec:
    source: file
    file: spec.schema.json
  output:
    source: file
    file: output.schema.json

examples:
- summary: List Azure load balancers
  content:
    apiVersion: v1
    kind: Step
    name: list-load-balancers
    image: relaysh/azure-network-step-load-balancer-list
    spec:
      azure:
        connection: !Connection { type: azure, name: my-azure-account }
      resourceGroup: !Parameter resourceGroup 