apiVersion: integration/v1
kind: Step
name: azure-network-step-nic-list
version: 1
summary: List NIC

description: |

build:
  apiVersion: build/v1
  kind: Docker

publish:
  repository: relaysh/azure-network-step-nic-list

schemas:
  spec:
    source: file
    file: spec.schema.json
  output:
    source: file
    file: output.schema.json