apiVersion: integration/v1
kind: Step
name: azure-network-step-nic-list
version: 1
summary: List NIC

description: Lists the Azure Network Interfaces in an account.
build:
  apiVersion: build/v1
  kind: Docker

publish:
  repository: relaysh/azure-network-step-nic-list

schemas:
  spec:
    source: file
    file: spec.schema.json
  output:
    source: file
    file: output.schema.json


examples:
- summary: List Azure network interfaces
  content:
    apiVersion: v1
    kind: Step
    name: list-nics
    image: relaysh/azure-network-step-nic-list
    spec:
      azure:
        connection: !Connection { type: azure, name: my-azure-account }
      resourceGroup: !Parameter resourceGroup