apiVersion: container/v1
kind: StepContainer
inherit: ../hack/defs/azure-python
title: List Azure Network Interfaces by SubscriptionId
description: >
  This task describes the Azure Network Interfaces in a given Subscription.
